### ISSUE TITLE
Lazyloading images

### ISSUE THREAD

**Issue by pixeliner** [silvia-odwyer/lightbox.js#1]
Hi,

I have a NextJs app and was willing to integrate lightbox into it.
For now, to show all images, I dynamically import (next/dynamic) each image with cloudinary (cropped image).
This way each image is about 30kb in size, instead of the 5 to 7mb original.

How can I use your lightbox when an image is clicked? and dynamically load the original image?
Cause each gallery is about 150 to 300 photos. So loading 2Gb of photos is a no go off course.

**Comment by silvia-odwyer** [comment]
@pixeliner Hi there! I've just added new functionality which will fix the issue. It has been included as part of a new version release. Firstly, update your `lightbox.js-react` NPM version to `0.0.9`.

Next, simply create an `images` array as shown below and include the links to the cropped, 30kb image and the original, high-resolution images. 

```js
  const images = [
    {
      title: 0,
      src: 'https://source.unsplash.com/2FiXtdnVhjQ/500x300',
      original: 'https://source.unsplash.com/2FiXtdnVhjQ/1200x900',
      caption: 'City skyline'
    },
    {
      title: 1,
      src: 'https://source.unsplash.com/kID9sxbJ3BQ/500x300',
      original: 'https://source.unsplash.com/kID9sxbJ3BQ/1200x900',
      caption: 'Biscuits displayed in woven basket'
    },
  ];
```
Then just pass this array of images to the `images` prop in the `<SlideshowLightbox>` component. Since the images are of high-resolution and may take a little longer to load for slower internet connections, a spinning loader can also be optionally be displayed until the image has been loaded. The `showLoader` prop should be set to `true` to enable this feature.
```js
    <SlideshowLightbox showLoader={true} images={images} className='container grid grid-cols-3 gap-2 mx-auto'>
     </SlideshowLightbox>
```

With this solution, the smaller images will be displayed first, and when the user clicks on an image, the high-resolution image will be dynamically loaded and displayed in the lightbox. 

Hope that helps, and let me know if you have any other questions or need any other assistance, I'm always glad to help out! 😄
