### ISSUE TITLE
[Feature Request] Trigger images to pop-up using button tag

### ISSUE THREAD

**Issue by permlap** [silvia-odwyer/lightbox.js#15]
Hi, 
Is it possible to create a lightbox that displays images when a button tag is clicked, or is it necessary to use an image tag? Currently, the lightbox only appears when the image tags are clicked. So, I am asking you to create a lightbox that is working with a button as well.
For example:
```
         <SlideshowLightbox
          lightboxIdentifier="lightbox1"
          framework="next"
          images={images}
        >
          <button>Click</button>
         </SlideshowLightbox>
```

**Comment by silvia-odwyer** [comment]
@permlap It's now possible to display the lightbox using an open/close button in Next.js. If you uninstall your current version of Lightbox.js and install the latest version, the feature should be available.

To open the lightbox, just set the `open `prop to `true `and to close the lightbox, set the `open` prop to `false`.  You can also set which image the lightbox should open at via setting a numeric value for the `startingSlideIndex` prop.

When the lightbox is closed, an `onClose` event is triggered, so that the `open` prop can be re-initialized back to `false`.

I've also created a quick example:
```js
export const DemoExample = () => {
  const [open, setOpen] = useState(false);
  const images = [
    {
      src: 'https://source.unsplash.com/sQZ_A17cufs/8549x8711',
      alt: 'Mechanical keyboard with white keycaps.',
    },
    {
      src: 'https://source.unsplash.com/rsAeSMzOX9Y/8768x8512',
      alt: 'Mechanical keyboard with white, pastel green and red keycaps.',
    },
    {
      src: 'https://source.unsplash.com/Z6SXt1v5tP8/768x512',
      alt: 'Mechanical keyboard with white, pastel pink, yellow and red keycaps.',
    },
  ]
  
  return (
    <div>
      <button onClick={() => {setOpen(!open)}}>Open Lightbox</button>
       <SlideshowLightbox
          lightboxIdentifier="lightbox1"
          framework="next"
          images={images}
          showLoader={true}
          open={open}
          onClose={() => {setOpen(false)}}
        />
    </div>
  )
}
```

Hopefully that helps, and if you have any queries, just let me know. ✅

**Comment by permlap** [comment]
That's great! thanks for your hard work!
