### ISSUE TITLE
Using the upper 15% of the screen

### ISSUE THREAD

**Issue by Maskoe** [silvia-odwyer/lightbox.js#2]
I would like an option where my Image would use the full screen. This is fully zoomed in, but the top ist still a black bar. Seems like a waste of screen space.

I get that the navigation is there, but it could just be overlayed on top of the image. Just like the forward/backward buttons.

![image](https://user-images.githubusercontent.com/27558844/202906779-45e9b412-73c3-4899-848e-2eb0c4c59b2d.png)

Thank you.

**Comment by silvia-odwyer** [comment]
@Maskoe Hi Mirco! Thanks for opening this issue, that's an excellent point about supporting full-screen images. I'll get working on this today, and will let you know when I've added support for this ✅

**Comment by silvia-odwyer** [comment]
@Maskoe I've just published a new version of the library which has full-screen image support. 
To enable this feature, simply set the `fullScreen ` prop to `true`:
```html
<SlideshowLightbox fullScreen={true}>
...
</SlideshowLightbox>
```

Due to the images being full-screen, the icons in the top-right corner will be displayed over the images. If you wish to update the icons or remove the controls entirely to leave just the close icon, I've included the props to update below.
 
If you'd like to remove the navigation control icons in the top-right corner of the screen, you can set the `showControls` prop to `false`:

```html
<SlideshowLightbox showControls={false}>
...
</SlideshowLightbox>
```

Or you can change the color of the icons through setting a value for the `iconColor ` prop:

```html
<SlideshowLightbox iconColor="silver">
...
</SlideshowLightbox>
```

If you'd like any updates, be sure to let me know, as I'm always happy to help. Thanks, Mirco! 😄

**Comment by Maskoe** [comment]
works great
and fits what I'm building so much better 👍
