### ISSUE TITLE
showSlideshowIcon prop is not used when more than one image is present

### ISSUE THREAD

**Issue by annarack** [silvia-odwyer/lightbox.js#23]
https://github.com/silvia-odwyer/lightbox.js/blob/cd122ecf95c7cd7fcaa3a1830bbfc7c223cd6ed7/lightbox.js-react/src/SlideshowLightbox.tsx#L335

Hey! 
We currently need a Lightbox for images. Since we are using nextJS and it doesn't need to be a gallery, we used the SlideshowLightbox instead of the Image component. The idea was to then simply hide the slideshowIcon and the arrows, but the showSlideshowIcon property is not working as soon as there are multiple images assigned. 

I guess the ideal way would be to have the Image Component work with NextJS Images, but as far as I can see, this is not possible yet, or?

**Comment by silvia-odwyer** [comment]
@annarack Hi Anna,
Thanks for opening this issue, that's a great point about adding Next.js support to the Image component. I will add this functionality to the component, it will be a part of the next version release of the library in the next few days or so.

Additionally, I will also update the SlideshowLightbox component so that the `showSlideshowIcon` prop will be set to the value specified, and not determined by the number of images in the lightbox, as it is currently.

Hopefully that helps, and let me know if you have any queries.

**Comment by silvia-odwyer** [comment]
@annarack Hi Anna,
The library has been updated and Lightbox.js now has Next.js support. If you uninstall your current version of the library and reinstall the latest version, the new feature will be available.

To prevent naming conflicts with the Next.js Image component, it is renamed in this example:
```js
import { Image as LightboxjsImage} from 'lightbox.js-react'
```

Then, just create an image like so:
```js
let image = {
  src: "https://source.unsplash.com/Bkci_8qcdvQ/1700x950",
  alt: "A mountain range overlooked by a blue sky and clouds, with a forest in the foreground"
}
```

The Next.js Image component can be included within the LightboxjsImage component. A `lightboxIdentifier` also needs to be added to each LightboxjsImage component, along with a matching value for the image's data-lightboxjs attribute.

Here's the JSX:
```jsx
<LightboxjsImage modalClose="clickOutside" lightboxIdentifier="lightbox1" framework="next" image={image}>
  <Image
      src={image.src}
      alt={image.alt}
      height={500}
      width={500}
      quality={80}
      data-lightboxjs="lightbox1"
    />
</LightboxjsImage>
```
Hopefully that helps, and if you have any other feature requests, just let me know.
