### ISSUE TITLE
react, custom button to open image preview

### ISSUE THREAD

**Issue by dgastudio** [silvia-odwyer/lightbox.js#25]
Hello, is that possible to make it work based on this code?

![CleanShot 2023-07-08 at 09 51 52@2x](https://github.com/silvia-odwyer/lightbox.js/assets/161524/e99a6bd2-25b3-437c-bbab-bdbf81fb130d)

means, the button which one is coming just after the image, will trigger the modal?

thank you

**Comment by silvia-odwyer** [comment]
@dgastudio Hi Alexei,
It's possible to open the lightbox by toggling the `open` prop passed to the SlideshowLightbox component. When the corresponding button is clicked, the starting index of the lightbox could be set to the same index as the one of the image clicked:

```
<SlideshowLightbox 
  open={isOpen} 
  startingSlideIndex={startingIndex}
  images={images}
  onClose={() => setIsOpen(false)} 
  lightboxIdentifier="lbox1">
 ...
</SlideshowLightbox>
```

To make use of this functionality, you would need to also pass an array of images to the SlideshowLightbox component's `images` prop (as shown in the JSX above). I see that you have an array of items, so you could modify the array's object's attributes to match the ones below: 
```js
const images = [
  {
    src: 'https://source.unsplash.com/sQZ_A17cufs/549x711',
    alt: 'Mechanical keyboard with white keycaps.',
  },
  {
    src: 'https://source.unsplash.com/rsAeSMzOX9Y/768x512',
    alt: 'Mechanical keyboard with white, pastel green and red keycaps.',
  },
  {
    src: 'https://source.unsplash.com/Z6SXt1v5tP8/768x512',
    alt: 'Mechanical keyboard with white, pastel pink, yellow and red keycaps.',
  },
]

```

And here's the remaining code:
```js
 let [isOpen, setIsOpen] = useState(false);
 let [startingIndex, setStartingIndex] = useState(0);
```

When the button is clicked, you would then need to update the `startingSlideIndex` prop passed to the SlideshowLightbox component, so that the lightbox opens to the same index as the image clicked.

```jsx
<Button onClick={() =>  {setIsOpen(true); setStartingIndex(k)}}> 
   ...
</Button>
```

Hopefully that helps, and let me know if you have any queries.

**Comment by dgastudio** [comment]
thank you very much @silvia-odwyer 
but it will not work for me, as i have a pretty complicated nested img wrapper (component)
nevermind, we will refactor a little bit the html code, so the button will be removed, thank you!

**Comment by dgastudio** [comment]
@silvia-odwyer 
i have a better solution, pretty much exactly the same as your example, but without passing the images array
![CleanShot 2023-07-08 at 10 20 15@2x](https://github.com/silvia-odwyer/lightbox.js/assets/161524/82a347c6-4f46-4efa-8363-680cb4826248)

**Comment by silvia-odwyer** [comment]
@dgastudio That's a great solution, I'm glad it's working for you now! Once the `data-lightboxjs` attribute is added to the image, the lightbox component will create an internal array of images, so that you don't have to pass them via an `images` prop. I'm glad the feature you wanted can be implemented ✅
