### ISSUE TITLE
Stop propagation of ESC keypress event

### ISSUE THREAD

**Issue by andreisocaciu** [silvia-odwyer/lightbox.js#31]
I need to stop this event propagating, but I don't have access to it. 

Could you add the original event to `onClose` when closing by pressing the ESC key?

**Comment by silvia-odwyer** [comment]
@andreisocaciu Hi Andrei,
I've just published a new version of the library, which contains the updated code, could you check to see if it works for you?

I've added `event.stopPropagation()` and `event.preventDefault()` to the keypress event handler for the ESC key, as shown [here](https://github.com/silvia-odwyer/lightbox.js/blob/2d70b31c87d9e7a1a287d954f8c99d3140593eea/lightbox.js-react/src/SlideshowLightbox.tsx#L1850). Let me know if it's not stopping the propagation of the keypress event though.

**Comment by andreisocaciu** [comment]
I installed version `0.7.9` and it still closes my MUI modal that is behind the slideshow when I press the Escape key.

**Comment by silvia-odwyer** [comment]
@andreisocaciu I've identified what may be causing the issue. Currently, the MUI modal prevents focus from leaving the modal while it is opened, however when the lightbox is open, it requires an element in the lightbox to be in focus.

Therefore, you could set the `disableEnforceFocus` prop to `true` for the MUI modal, so that the focus can be moved to the lightbox while the modal is open at the same time. Then, when the lightbox is closed, the focus is moved back to the MUI modal. 

```jsx
<Modal
        open={modalOpen}
        onClose={handleClose}
        disableEnforceFocus={true}
        aria-labelledby="modal-modal-title"
        aria-describedby="modal-modal-description">
...
      </Modal>
```

I've added new code to the lightbox to focus the lightbox modal, so you would need to install the latest version for this to work.

With this, the lightbox now closes when the ESC key is pressed while the MUI modal remains open. Hopefully that helps.

**Comment by andreisocaciu** [comment]
This solves my issue, thanks for all the help! 

Only one minor comment: now that the focus can move to the lightbox container, it shows a blue outline. But I will remove it with CSS.
