### ISSUE TITLE
Combining all Image-Components on Page

### ISSUE THREAD

**Issue by DominikProbst** [silvia-odwyer/lightbox.js#35]
Hey Silvia,
it would be nice to combine all Images inside the Image Component to get a Slideshow.
Also it would be great to define the width and height of my image, like the NextJS Image-Component.
`<Image src={src} width={1920} height={1080} alt="..." />`

Example: 
I've got a page with e.g. 10 single Images and for them I use your Image-Component.
It would be nice to see all of them (maybe with the same slideshow-id) when I click on one.

Another way I can think of is to add the children props to your Image-Component, so I could wrap it around my NextJS-Image.
```
<YourImage image={{src: "xyz"}}>
    <NextJSImage .... />
</YourImage>
```

Thanks in advance :-)

**Comment by silvia-odwyer** [comment]
@DominikProbst Hi Dominik,
I've added new `width` and `height` props to the `Image` component, so that you can now specify the dimensions of the image.

For Next.js images, you can wrap these in the Image component also, just take a look at [this guide](https://github.com/silvia-odwyer/lightbox.js/issues/23#issuecomment-1630688778) on how to implement that.

However, for your use case, if you'd like to include multiple images in the lightbox rather than just one, I would recommend to wrap the page in the `SlideshowLightbox` component, and then add a `data-lightboxjs` lightbox identifier to any image you'd like to display in the lightbox. The `Image` component below is the Next.js Image component:

```jsx
<SlideshowLightbox 
    showThumbnails={true}
    lightboxIdentifier="lbox1"
    framework="next"
    images={images}>
   <div>
       <h1>Content</h1>
          {images.map((image, index) => (
            <Image
              src={image.src}
              alt={image.alt}
              data-lightboxjs="lbox1"
              height={500}
              width={500}
              quality={80}
            />
      ))}
</div>
</SlideshowLightbox>
```
You could place any content within the SlideshowLightbox component, as it'll only check for img elements and whether these have the data attribute. Only images with the data attribute will be included. This way, there is one place where you can configure the various options for the lightbox. 

The library's Image component creates a SlideshowLightbox instance, so if you were to add multiple Images and wish to add these to the same lightbox, multiple instances of the SlideshowLightbox would be created. That's why I'd recommend taking a look at the solution above instead.

Hopefully that helps, and let me know if you have any queries.

**Comment by DominikProbst** [comment]
Hi @silvia-odwyer,
many thanks!

The lightbox is opening fine, but I got some errors in the terminal and also the lightbox visual apperance is broken. Maybe you have a hint for me how to fix that:

<img width="1364" alt="Bildschirmfoto 2023-09-28 um 17 23 39" src="https://github.com/silvia-odwyer/lightbox.js/assets/88315846/c4d5a641-5bff-4fd8
<img width="2558" alt="Bildschirmfoto 2023-09-28 um 17 24 39" src="https://github.com/silvia-odwyer/lightbox.js/assets/88315846/a1f8af0a-e13a-4f3b-81e5-096439ccbc60">
-80ca-f60ea5336f2c">


That is my code:

`'use client';

import {useEffect} from "react";
import {initLightboxJS, SlideshowLightbox} from "lightbox.js-react";

export default function RenderContent({content, images} : {content: string, images: []}) {
	useEffect(() => {
		initLightboxJS('MY-KEY', 'team');
	}, []);
	
	return (
		<SlideshowLightbox
			images={images}
			framework="next"
			lightboxIdentifier="lightbox"
		>
			<div className="grid grid-cols-1 gap-4 content" dangerouslySetInnerHTML={{__html: content}} />
		</SlideshowLightbox>
	);
}`

**content** is my HTML, where every <img>-Tag has data-lightboxjs="lightbox"


Thanks in advance!

**Comment by silvia-odwyer** [comment]
@DominikProbst Hi Dominik,
The console warning appears to be related to this [issue here](https://github.com/axios/axios/issues/5716). There's a [suggested solution](https://github.com/axios/axios/issues/5716#issuecomment-1636730863) in the issue too, which removes the warnings. Perhaps it might solve the warnings for your project also, hopefully 😄

**Comment by DominikProbst** [comment]
@silvia-odwyer Thanks Silvia, that suggested solution worked. Thanks for your awesome work mate :-)
