### ISSUE TITLE
props.image.title on next.js

### ISSUE THREAD

**Issue by milesscherrer** [silvia-odwyer/lightbox.js#54]
Just getting 

TypeError: undefined is not an object (evaluating 'props.image.title')

`<SlideshowLightbox lightboxIdentifier="lightbox1" framework="next" images={photos}>
            {photos.map((image) => (
              <Image
                src={image.src}
                alt={image.alt}
                title={image.title}
                height={500}
                width={500}
                data-lightboxjs="lightbox1"
                quality={80}
              />
          ))}
      </SlideshowLightbox> `

**Comment by silvia-odwyer** [comment]
@milesscherrer Hi there! Are you using the Image component from Lightbox.js? You would get this error if you're using the Lightbox.js Image component and an `image` prop isn't passed to the component. 

If you're already using the SlideshowLightbox component, then there is no need to make use of the Lightbox.js Image component.  Just take a look at your imports, and switch it for the following instead, so that the Next.js Image component is used instead.
```js
import Image from "next/image";
```

Hopefully that helps, and let me know if you have any queries.
