### ISSUE TITLE
Bug:  imgAnimation with fullScreen

### ISSUE THREAD

**Issue by sun0225SUN** [silvia-odwyer/lightbox.js#56]
When I set the fullScreen property of SlideshowLightbox to true, imgAnimation is forced to "fade".

**Comment by silvia-odwyer** [comment]
@sun0225SUN Hi Guoqi,
Thanks for opening this issue. I just updated the code so that you can specify the animation style when the fullScreen property is set to true. The default is "fade", but if you set the imgAnimation property to "imgDrag", the images will be swipeable instead.

```jsx
<SlideshowLightbox
imgAnimation="imgDrag">
...
</SlideshowLightbox> 
```
I've just published a new version of the library which has this functionality. If you uninstall your current version and re-install the latest version, the new feature should be included. 
Hopefully that helps, and let me know if you have any queries.

**Comment by sun0225SUN** [comment]
Thank you for solving my problem successfully. Have a nice day.
